### ISSUE TITLE
UserDialogService.HideLoading() does not dismiss loading.

### ISSUE THREAD

**Issue by Thalarion** [aritchie/acr-xamarin-forms#101]

**Comment by aritchie** [comment]
You're going to have to include the code that is giving you the issue.

**Comment by Thalarion** [comment]
Look at the code below.
UserDialogService.Loading(title:"Entrando");


            try
            {


                switch (provider)
                {
                    case LoginProviderEnum.Facebook:


                        if (!(await _service.Authorize(provider)))
                        {
                            UserDialogService.HideLoading();


                            MessagingCenter.Send(this, "Register");
                        }
                        else
                        {
                            UserDialogService.HideLoading();


                            Application.Current.Properties["logged"] = true;


                            MessagingCenter.Send(this, "LoggedIn");
                        }


                        break;


                    case LoginProviderEnum.Custom:


                        await Service.Authorize(provider, Model.Email, Model.Password, Model.Email);


                        Application.Current.Properties["logged"] = true;


                        MessagingCenter.Send(this, "LoggedIn");


                        break;
                }


                UserDialogService.HideLoading();
User service is a property of my viewmodel that is of Type IUserDialogService resolve by dependency Service.
The method HideLoading does not dismiss the loading on iOS,Android and WindowsPhone.
Best reguards,Vinicius Henrique.
Date: Wed, 25 Mar 2015 05:22:46 -0700

**Comment by aritchie** [comment]
This is not how this was intended to be used.  Loading returns a disposable and is self contained.  If you want to use HideLoading, then you should be using ShowLoading().  This is a managed instance.  

Please review the samples.
