### ISSUE TITLE
Barcode scan - memory leak on Android

### ISSUE THREAD

**Issue by grisha-v** [aritchie/acr-xamarin-forms#104]
Hello,
This is connected to issue #99.
I succeeded to reproduce this bug in a sample project and Xamarin support thinks that the memory leak is inside the barcode scanning page. Please look at my last comment to issue #99 - I attached there the answer I got from Xamarin.

Thanks

**Comment by aritchie** [comment]
You are going to have to give me a reproducible cast with code!  I have not experienced the issue at all.

**Comment by grisha-v** [comment]
I mentioned the link to the project in the comment to #99 issue.
It's here:
http://www.filedropper.com/listtest

The project consists of two almost identical pages with list and “scan barcode” button, so that tapping a list record switches between pages.

To reproduce the issue, one need to tap “scan barcode” button, then hardware back button to return to list, then tap list cell to switch to the second page, “scan barcode” there and back to list. After 3-4 such cycles, the application crashes…

**Comment by grisha-v** [comment]
I found that my repro project upload was deleted by the hosting service.
I uploaded it again to another host here:
http://s000.tinyupload.com/index.php?file_id=20120254684748633410
Thanks.

**Comment by aritchie** [comment]
I profiled memory under DDMS and it looks fine (in my own sample, your project is larger than it needs to be).  Xamarin's profiler is buggy at best (v0.12).  In any case, this library is a wrapper around zxing, so if you are determined to pursue this issue, you will have to talk to others.  Xamarin forms has many memory issues and you should probably focus your efforts there first.
