### ISSUE TITLE
Cancel button on ActionSheet for Win Phone

### ISSUE THREAD

**Issue by Brosten** [aritchie/acr-xamarin-forms#105]
Why does the cancel-button on the actionsheet for WinPhone has a double border? Doesn't look that nice =(

![cancel](https://cloud.githubusercontent.com/assets/10629345/6827731/991de942-d309-11e4-839e-95f2040b05d0.png)

**Comment by aritchie** [comment]
Check your styles

**Comment by Brosten** [comment]
- I created a brand new Project, (Blank App (Xamarin.Forms Portable)
- Installed the following Nugets:
* Xamarin.Forms 1.4.0.6341
* Windows Phone Toolkit 4.2013.08.16
* ACR User Dialogs Plugin for Xamarin and Windows 3.1.0
- Added the code below.

But I still get the strange looking Cancel-button

--------------------- CODE ----------------------------
	public class App : Application
	{
		public App()
		{
			// The root page of your application
			MainPage = new ContentPage
			{
				Content = new StackLayout
				{
					VerticalOptions = LayoutOptions.Center,
					Children = {
						new Button
						{
							Text = "Action",
							Command = new Command(ShowActionSheet)
						}
					}
				}
			};
		}

		private void ShowActionSheet()
		{
			ActionSheetConfig actionSheetConfig = new ActionSheetConfig();
			actionSheetConfig.Add("Alt 1", () => { });
			actionSheetConfig.Add("Alt 2", () => { });
			actionSheetConfig.SetCancel("Avbryt", () => { });

			UserDialogs.Instance.ActionSheet(actionSheetConfig);
		}
	}

![cancel2](https://cloud.githubusercontent.com/assets/10629345/6841473/9617e43c-d38b-11e4-8e14-7baedc3b46b0.png)

**Comment by aritchie** [comment]
This library is now deprecated
