### ISSUE TITLE
iOS7 bug (UserDialogService) with UIAlertView, title & buttons are never assigned.

### ISSUE THREAD

**Issue by kladis** [aritchie/acr-xamarin-forms#106]
Fix UserDialogService.cs:

```C#
        public override void Login(LoginConfig config) {
        ...
        var dlg = new UIAlertView { AlertViewStyle = UIAlertViewStyle.LoginAndPasswordInput };
```

Needs to be with (or something like this):
```C#
        UIAlertView (config.Title ?? String.Empty, config.Message, null, config.CancelText, config.OkText)
```

**Comment by aritchie** [comment]
Use Acr.UserDialogs (https://github.com/aritchie/userdialogs).  It is available on nuget.  It is the replacement for this library

**Comment by kladis** [comment]
They has the same bug. Anyway I thought that they are used your source code.

**Comment by aritchie** [comment]
I'll fix it on the other library when I have time

**Comment by kladis** [comment]
Thanks for the update. But now UIAlertView subtitle doesn't exists still. If you're need some help with iOS features, you're welcome, I would join.

**Comment by aritchie** [comment]
I tested the login method on iOS7 and looks fine in Acr.UserDialogs.  Ensure you are using 3.1.0.  If you are using that library, please send code with the issue.
