### ISSUE TITLE
Prompt dialog and Numeric Keyboard support

### ISSUE THREAD

**Issue by Garpo001** [aritchie/acr-xamarin-forms#107]
Would it be possible to build in support for your prompt dialogs to assign specific keyboards. For example, I would like to create a pin dialog that will require the Numeric only keyboard on devices. The secure options work nicely for this. I have had a look and could not find a way to do this currently.

**Comment by aritchie** [comment]
Yes - use Acr.UserDialogs (https://github.com/aritchie/userdialogs - also on nuget). This functionality is already there

**Comment by Garpo001** [comment]
Thank you. Are those replacing this repository?

**Comment by aritchie** [comment]
yes
