### ISSUE TITLE
SignaturePad Problem if enable debugging is not checked

### ISSUE THREAD

**Issue by cvarelae** [aritchie/acr-xamarin-forms#109]
Hello mates,

I have a problem with the signatureService. 

I add this line after del Forms.Init() in the AppDelegate:
App.SignatureService = new Acr.XamForms.SignaturePad.iOS.SignatureService ();

If i have checked the option "Enable developer instrumentation" and "enable debugging" in the Options-> "iOS Build" in mode release the app works perfectly, but if i unchecked this options the app does not run.

If I comment the line of the signature service the app runs perfectly, but the signature does not work.

In the App.cs of the PCL I have this:
public static Acr.XamForms.SignaturePad.ISignatureService SignatureService { get; set; }

It is the variable that i initialize on the AppDelegate.

Any idea to solve this?

Thanks a lot in advance!

**Comment by aritchie** [comment]
What doesn't run?  What is the exception?  You need to file your defects with much more detail!!

You should read the following as I'm expecting the issue that you are having has been answered many times:

https://github.com/aritchie/acr-xamarin-forms/issues/86

**Comment by cvarelae** [comment]
The ipa is generated, but when i tap on the icon of the app, the app open and then close itself.

You only see the black screen of launching.

**Comment by aritchie** [comment]
Enable linking in debug mode.  If you do know how to do that, you need to read up on the linker with xamarin.  

#86 will answer your problem.

**Comment by cvarelae** [comment]
I put this in a iOS interface that i call at the begin of the app:

if (App.SignatureService == null) {
	App.SignatureService = new Acr.XamForms.SignaturePad.iOS.SignatureService (); //This line it was in the app delegate
}

And now it is working!! 

Thanks a lot again!!
