### ISSUE TITLE
SignaturePad: Null reference exception in OnCreate (Android)

### ISSUE THREAD

**Issue by htxryan** [aritchie/acr-xamarin-forms#110]
I'm attempting to use ISignatureService, and I'm running into an issue.

In my code, when I call:
```
var result = await _signatureService.Request();
```
I get the following exception:

```
04-16 10:54:00.388 E/mono-rt (10226): [ERROR] FATAL UNHANDLED EXCEPTION: System.NullReferenceException: Object reference not set to an instance of an object
04-16 10:54:00.388 E/mono-rt (10226):   at Acr.XamForms.SignaturePad.Droid.SignaturePadActivity.OnCreate (Android.OS.Bundle bundle) [0x00000] in <filename unknown>:0 
04-16 10:54:00.388 E/mono-rt (10226):   at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_ (IntPtr jnienv, IntPtr native__this, IntPtr native_savedInstanceState) [0x00011] in /Users/builder/data/lanes/1353/86274adf/source/monodroid/src/Mono.Android/platforms/android-21/src/generated/Android.App.Activity.cs:2380 
04-16 10:54:00.388 E/mono-rt (10226):   at (wrapper dynamic-method) object:0a32853f-5f01-48c0-9bb1-1514029e5d64 (intptr,intptr,intptr)
```

I've installed the nuget package in my Droid project and my PCL. I've ensured that my IOC container (SimpleIOC) is properly registering the dependency. I also tried the suggestion from #86 with no luck.

Any help is greatly appreciated!

**Comment by aritchie** [comment]
Have you changed the DefaultConfiguration at all?  ie. SignaturePadConfiguration.Default.CaptionText = "something"; ?

**Comment by htxryan** [comment]
Thanks for the quick reply.

No, there are no changes to any configuration values. The line below, aside from IOC container stuff, is the only SignaturePad-related line of code in the application:

```
var result = await _signatureService.Request();
```

**Comment by aritchie** [comment]
Is this on a device or emulator?  Do the samples work for you?

**Comment by htxryan** [comment]
I tried the samples, and they work. 

This one's on me. I tracked the issue down to the way dependency injection (SimpleIoC) was set up. Thanks again for your help!

**Comment by aritchie** [comment]
Thanks for letting me know. Glad you found the issue
