### ISSUE TITLE
Infinite loop in progress dialog with progress reporter

### ISSUE THREAD

**Issue by alexrainman** [aritchie/acr-xamarin-forms#111]
I am trying to use progress dialog with a progress reporter. It was working but it's not working anymore after the latest update. Here's my code:

using (var dlg = dialogService.Progress("Updating")) {
        var tasks = App.Web.CreateTaskForEachFileToDownload (files); // this return list of tasks
        var progress = new Progress<int> ();
        progress.ProgressChanged += (sender, value) => dlg.PercentComplete = value;
        // after debugging the code i checked that progress is reporting
        // if i comment the while, the task list is executed and the dlg dismiss
        while (dlg.PercentComplete < 100) {
                await App.Web.DownloadHandler (progress, tasks);
        }
}

public async Task DownloadHandler (IProgress<int> progressReporter, List<Task> tasks)
{
	int total = tasks.Count;
	while (tasks.Count > 0)
	{ 
		var task = await Task.WhenAny (tasks);
		tasks.Remove(task);
		if (progressReporter != null)
		{
			int p = 100 - (tasks.Count * 100) / total;
			progressReporter.Report(p);
		}
		try
		{ 
			await task;
		}
		catch (Exception exc)
		{
			System.Diagnostics.Debug.WriteLine(exc.Message);
		}
	}
}

**Comment by aritchie** [comment]
Considering I haven't actually made an update to this library in months, you may want to look into your code a bit more.  How do you know its an infinite loop?  What is the exception?  What library is the progress reporter from?

**Comment by alexrainman** [comment]
I got nuget update last month. Standard Progress in System.Runtime.Extensions. That's all the code i have, plus the code for the tasks itself. As i said, if i remove the while the code runs without any problem and the progress as i debugged the ProgressChanged delegate and DownloadHandler function. Can you provide example of how to use this with a progressReporter?

**Comment by alexrainman** [comment]
The example you provide is very simple and you change the PercentComplete inside the while, but, normally you want to use a progress dialog with a progress reporter related to downloading files or something like that.

**Comment by aritchie** [comment]
It doesn't matter where you set it as long as the dialog is active.  I use this for file downloading all the time.  If you are getting an infinite loop in your while loop, change your while loop.

**Comment by alexrainman** [comment]
Change it to what? Can you provide an example?

**Comment by aritchie** [comment]
I have no idea without debugging this code myself, which no offense, is beyond what I'm willing to do.

Do a little bit of upfront debugging and ensure that 100 is being reached.

**Comment by alexrainman** [comment]
100 percent is reached, i did debugging. It's the second time i report something with your library and the response is not so nice. Please, if you are going to provide open source stuff be open to help too even if the question is dumb. I hope i can use something else as soon as possible. Than you!

**Comment by aritchie** [comment]
The first time you reported something, I tried to give you an answer but I didn't know how to fix it myself.  It also wasn't a very solid use-case for me to even attempt fix.  Just because I don't think something is a defect OR I don't fix your problem for you, doesn't mean I'm not being nice.

The fact is, you have a while loop that you comment out. your problem goes away.  That is your code!

**Comment by alexrainman** [comment]
The While loop comes from your example my friend. You provided the way to use it. Thank you for your amazing library!

**Comment by aritchie** [comment]
Does the sample work for you?

The fact is, your code is stuck in the loop right now, not mine.  If you can find a defect in my code that does cause the issue, I will be more than happy to fix it.  If you want any form of help now or in the future, quit being a smart ass.  I don't have to help you at all.  I don't even have to provide this library, but I do.

**Comment by alexrainman** [comment]
Thank you.
