### ISSUE TITLE
Null object when calling LoadDrawPoints

### ISSUE THREAD

**Issue by williamrshepherd** [aritchie/acr-xamarin-forms#112]
Hello, 

I am currently using this library to support capturing signatures in a Xamarin Form project. I am getting an exception when trying to load DrawPoints form a file.

Stack Trace:
04-20 20:13:13.475 I/MonoDroid(10377): System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object
04-20 20:13:13.475 I/MonoDroid(10377):   at Acr.XamForms.SignaturePad.SignaturePadView.LoadDrawPoints (IEnumerable`1 drawPoints) [0x00000] in <filename unknown>:0 
04-20 20:13:13.475 I/MonoDroid(10377):   at App.Pages.DriverSignaturePage.DummyMethod (Ports.Messages.SetSignatureMessage message) [0x00011] in c:\Users\william.shepherd\DocumentsApp\Pages\DriverSignaturePage.xaml.cs:54 

Tthe control is declared in a xaml file as such:

<signaturePad:SignaturePadView
          x:Name="Signature"
          StyleId="DriverSignature"
          HeightRequest="320"
          WidthRequest="240"            
          BackgroundColor="White"              
          ClearText="Redo"
          ClearTextColor="Blue"              
          SignatureLineColor="Black"
          StrokeColor="Black"
          StrokeWidth="4" />

And a method is calling LoadDrawPoints from the code-behind:

private void DummyMethod(SetSignatureMessage message)
        {
            var points = message.DrawPoints;

            Signature.LoadDrawPoints(points);
            Signature.PromptText = "SetSignatureMessage Called";
        }

I would like to know if there is some setup that needs to take place before calling the LoadDrawPoints method. Setting the PrompText property works flawlessly (assuming I comment out the LoadDrawPoints method) and Saving the points from SignaturePad works just as well. The only problem seems to be with loading previously stored DrawPoints.

Any thoughts on what could be causing this behavior?

**Comment by williamrshepherd** [comment]
Is there any help you can provide on this issue?

**Comment by aritchie** [comment]
I'm not really supporting the control version of this anymore.  Too many issues working with xamarin forms.  While it certainly isn't the issue here, again, the control is dead until xamforms is in a better place
