### ISSUE TITLE
[WP] IBarCodeService's stream returns The component cannot be found. (Exception from HRESULT: 0x88982F50)

### ISSUE THREAD

**Issue by BladeMF** [aritchie/acr-xamarin-forms#113]
When using IBarCodeService.Create to create a barcode or qrcode and trying to use the stream like so:
var stream = service.Create(cfg);
ImageSource.FromStream(()=>{ return stream;});
I get the error The component cannot be found. (Exception from HRESULT: 0x88982F50). I tried different number of changes to the arguments - nothing.

**Comment by BladeMF** [comment]
Also tried the code with the code here in the samples project - still the same issue.

**Comment by aritchie** [comment]
Use acr.barcodes, this library is deprecated.  Can you also supply a full stack trace with anything you file

**Comment by BladeMF** [comment]
Sure. Thanks for the fast answer. Should I use Acr.Barcodes for scanning also?

**Comment by aritchie** [comment]
Yes.  It is a full replacement.

**Comment by BladeMF** [comment]
Thanks.
