### ISSUE TITLE
Xamarin Mobile 0.7.5

### ISSUE THREAD

**Issue by pawelpabich** [aritchie/acr-xamarin-forms#115]
Hi,

The latest version of  nuget package comes with Xamarin Mobile 0.7.1. Do you have any plan to upgrade this dependency to 0.7.5? Any recommendations how to have those two versions coexist ?

Thanks

Pawel

**Comment by aritchie** [comment]
I updated to this months ago and it is included right in the Niger package

**Comment by pawelpabich** [comment]
Hi,

I've just create a new XF app and go the latest version of the package 2.0.4 and it looks like it uses the old version of  Xamarin Mobile. Am I missing something ?

![image](https://cloud.githubusercontent.com/assets/347637/7348803/da7bb980-ed37-11e4-9c58-8efab00333d1.png)

**Comment by aritchie** [comment]
From the wp8 project

    <Reference Include="Xamarin.Mobile, Version=0.7.1.0, Culture=neutral, processorArchitecture=MSIL">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>..\Components\xamarin.mobile-0.7.5\lib\wp8\Xamarin.Mobile.dll</HintPath>
    </Reference>

They may not have updated the versioning with xammobile.  Just replace it manually if you are concerned about it.  I don't think there is much of an upgrade in the wp8 side anyhow.

**Comment by pawelpabich** [comment]
Yeah, I can hack it but I would rather not :).  I think I simply downgrade  Xamarin Mobile to 0.7.1

**Comment by aritchie** [comment]
I'm saying it isn't a bug.  I've included xamarin.mobile 0.75 from the component store (the path shows that).  Xamarin may not have updated the assembly signature.

**Comment by pawelpabich** [comment]
Ah, ok. Now it makes sense. I thought that you wanted me to change the Hintpath. 

Thanks for clarifying this.
