### ISSUE TITLE
ERROR Adding 'Acr.XamForms.Mobile 2.0.4' to Si.Project.XamForms.WinPhone

### ISSUE THREAD

**Issue by antonardelli** [aritchie/acr-xamarin-forms#118]
Hi,
sorry for this question but I haven't find any help on this.
I have  Windows Phone 8.1 Project (into a Xamarin Forms Solution) and I'd like to add this package to it, but in nuget console I get this error. Can you help Me?
Thanks.
---
Adding 'Acr.XamForms.Mobile 2.0.4' to Si.Project.XamForms.WinPhone.
Install-Package : Could not install package 'Acr.XamForms.Mobile 2.0.4'. You are trying to install this package into a project that targets 
'WindowsPhoneApp,Version=v8.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more 
information, contact the package author.

**Comment by aritchie** [comment]
The error message clearly states the issue.  It is unlikely that this library will ever be upgraded to wp81 as a number of features in it are wrapped around xamarin.mobile.  There are far better alternatives out in the wild now.

**Comment by antonardelli** [comment]
Thank you for your answer. Could you suggest me any better alternative for
this? Thanks
Il 07/Mag/2015 14:31, "Allan Ritchie" <notifications@github.com> ha scritto:
