### ISSUE TITLE
Acr.UserDialogs NullReferenceException on Windows Phone 8.1

### ISSUE THREAD

**Issue by pierceboggan** [aritchie/acr-xamarin-forms#124]
Hi Allan,

I'm currently getting a System.NullReferenceException when attempting to call `UserDialogs.Instance.ShowLoading ("Text")` on Windows Phone 8.1.

Thanks,
Pierce Boggan

**Comment by aritchie** [comment]
Full stacktrace please.

**Comment by vinguan** [comment]
Im having the same problem.When try to get the IUserDialogs from dependency service its all return null.

**Comment by aritchie** [comment]
@vinguan It isn't the same issue at all.  Read #86

**Comment by aritchie** [comment]
No luck reproducing this issue.  If you provide a stack trace and/or code sample, please open a new case over at https://github.com/aritchie/userdialogs

**Comment by javier-alvarez** [comment]
I have the same problem. The wp8 lib doesn't work in wp8.1

**Comment by aritchie** [comment]
Please report with a full stack trace as I have requested several times I this thread already.  No stack trace = no fix.
