### ISSUE TITLE
SignaturePad saved image problem

### ISSUE THREAD

**Issue by tbitowt** [aritchie/acr-xamarin-forms#125]
Hi,

I have tried to use your software and found some problems. Basically, in case of Jpg image, I'm receiving black image, in case of Png image, I'm receiving image with transparent backgound and black signature.
```
SignaturePadConfiguration c = new SignaturePadConfiguration();
c.ImageType = ImageFormatType.Png;
SignatureResult signatureResult = await DependencyService.Get<ISignatureService>().Request(c);
OnSignatureCompleted(signatureResult);
```

Handling:

```
var file =
	await FileSystem.Current.LocalStorage.CreateFileAsync(DateTime.Now.ToString("yy-MM-dd hh_mm_ss") + ".png",
		CreationCollisionOption.GenerateUniqueName, CancellationToken.None);
using (var fs = await file.OpenAsync(FileAccess.ReadAndWrite, CancellationToken.None))
{
	BinaryReader reader = new BinaryReader(result.GetStream());
	var signatureBytes = reader.ReadBytes((int) fs.Length);
	reader.Dispose();
	result.GetStream().CopyTo(fs);
}
```

Both : signature.tmp and my created file has same wrong results

Tested on Samsung Galaxy S5, but I don't think it's helpful.

**Comment by aritchie** [comment]
This is the expected behaviour.  Change the colours accordingly if you are using jpg.

**Comment by tbitowt** [comment]
SO, could you specify how should I handle that? For both: png and jpg?

**Comment by aritchie** [comment]
Set the background and signature colors on the config object.

**Comment by tbitowt** [comment]
I have set following:
```
	c.SignatureBackgroundColor = Color.White;
	c.MainBackgroundColor = Color.White;
	c.SignatureLineColor = Color.Black;
	c.StrokeColor = Color.Black;
```

For both: jpg and png types. Results are same: png has transparent background, black signature, jpg is whole black

**Comment by aritchie** [comment]
So use PNG for now.  You are welcome to submit a fix in the meantime or wait until I have time to look into this.  I have no active dev against signatures right now, so it may be a while.
