### ISSUE TITLE
How to use it in a PCL no Xamarin Forms

### ISSUE THREAD

**Issue by alexrainman** [aritchie/acr-xamarin-forms#126]
Can you help? Thanks.

**Comment by aritchie** [comment]
I'm not entirely sure if you mean for something like unit testing or in another app where xamforms/mvvmcross etc are not available?

If you use Acr.UserDialogs (new nuget package and repo https://github.com/artichie/userdialogs ), xamforms is not required at all.

**Comment by alexrainman** [comment]
I just found the way:

if (UserDialogs.Instance == null) {
    UserDialogs.Init ();
}

Thank you!

**Comment by alexrainman** [comment]
I was just trying to start it on my iOS app and use the instance on my PCL viewmodels. Its working now. Thansk for the quick response.

**Comment by aritchie** [comment]
np
