### ISSUE TITLE
SignaturePad doesn't support for Windows 8.1

### ISSUE THREAD

**Issue by cdamose** [aritchie/acr-xamarin-forms#128]

**Comment by aritchie** [comment]
I never released a package for windows phone because I never finished the implementation.

**Comment by cdamose** [comment]
could you please suggest any work around?
i really need to finish this with in two days

**Comment by aritchie** [comment]
Implement windows phone support.  It was never implemented on windows phone

**Comment by cdamose** [comment]
i have one doubt, is this signature pad support windows implementation?

**Comment by aritchie** [comment]
Not sure.  You'd have to go take a look at xamarin signaturepad

**Comment by cdamose** [comment]
Thank you for spent your time
