### ISSUE TITLE
Dependancy cause install fail

### ISSUE THREAD

**Issue by katomic** [aritchie/acr-xamarin-forms#130]
Using VS2013, Xamarin Forms in VS, PCL with iOS and Xamarin.

See my Package manager console text below:
Install-Package Acr.XamForms.SignaturePad
Attempting to resolve dependency 'Xamarin.Forms (≥ 1.4.2.6359 && < 2.0)'.
Installing 'Acr.XamForms.SignaturePad 2.0.5'.
Successfully installed 'Acr.XamForms.SignaturePad 2.0.5'.
Install failed. Rolling back...
Install-Package : Updating 'Xamarin.Forms 1.4.4.6392' to 'Xamarin.Forms 1.4.3.6374' failed. Unable to find a version of 'XLabs.Forms' that is compatible with 'Xamarin.Forms 1.4.3.6374'.
At line:1 char:17
+  Install-Package <<<<  Acr.XamForms.SignaturePad
    + CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidOperationException
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand

**Comment by aritchie** [comment]
Reference #136
