### ISSUE TITLE
Samples don't build

### ISSUE THREAD

**Issue by kentcb** [aritchie/acr-xamarin-forms#132]
The sig pad samples don't even build. There are missing dependencies, such as `IFileSystem` and `IUserDialogService`.

**Comment by aritchie** [comment]
This repo isn't maintained right now.  Everything has been redirected or broken up to different areas listed in the readme.md

**Comment by kentcb** [comment]
Thanks @aritchie , but where is the XF signature pad view now? The readme just links to the native signature pad with no XF wrapper.

Basically I've got an issue where hosting the signature pad inside a `ScrollView` in XF isn't working. The touch events are being processed by the `ScrollView` rather than the `SignaturePadView` and I'm trying to figure out where the problem actually resides. Any thoughts?

**Comment by aritchie** [comment]
The signature pad wrapper is still in this repo, but not actively maintained.  I had numerous issues with the underlying signature pad native view.  The issue you are looking to resolve likely resides here: https://github.com/xamarin/SignaturePad

**Comment by kentcb** [comment]
Cool, thanks. FYI, I've just fixed this in [this PR](https://github.com/xamarin/SignaturePad/pull/22).
