### ISSUE TITLE
SignaturePad not working on iOS (Xamarin.Forms 1.5.1)

### ISSUE THREAD

**Issue by fcogutierrez** [aritchie/acr-xamarin-forms#138]
Hi Guys.

I have Xamarin.Forms 1.5.1.6471 version and the plugin is not working on iOS. Only it draws some points but not the full lines.

However, in Android it works fine.

I installed the nuget library in Core, iOS and Android projects and used this XAML:

            <acr:SignaturePadView
                x:Name="padView"
                HeightRequest="320"
                WidthRequest="240"
            
                BackgroundColor="White"
                CaptionText="Caption This"
                CaptionTextColor="Black"
                ClearText="Clear Me!"
                ClearTextColor="Red"
                PromptText="Prompt Here"
                PromptTextColor="Red"
                SignatureLineColor="Aqua"
                StrokeColor="Black"
                StrokeWidth="2"
            />

Must I do something more? Is there some workaround or fix available?

Thanks to all.

**Comment by aritchie** [comment]
The problem is currently unknown.  #136 is the bug to follow.
