### ISSUE TITLE
Toast on iOS doesn't use appropriate theme

### ISSUE THREAD

**Issue by ChaseFlorell** [aritchie/acr-xamarin-forms#3]
Not sure if the title is correct, sorry for that. I love your project, and first want to say it's saved me a ton of time not having to write it myself.

We use a lot of toast for things like "Network Offline". The toast on Android is good, however the toast on iOS doesn't seem to use the right theme. We're using the light theme, but the toast has a white background, and it makes it hard to notice the toast when it pops up. Is there a way for the toast to detect the theme and set the background accordingly?

**Comment by aritchie** [comment]
This has been added to Acr.UserDialogs 3.2.0 which will be on nuget shortly
