### ISSUE TITLE
SignatureService Load

### ISSUE THREAD

**Issue by scotru** [aritchie/acr-xamarin-forms#35]
First, thanks sharing this great library.  I hope that Xamarin includes some of your work in future releases.  I had just begun building a custom renderer for SignaturePad in Xamarin Forms when I found you'd already done it.

I notice that you currently have the Load method on the SignaturePadService remarked out and I was wondering why?  I'd like to use this functionality.

    //public override void Load(IEnumerable<DrawPoint> points) {
    //    var controller = new SignatureServiceController(this.Configuration, points);
    //    this.Show(controller);
    //}

**Comment by panjevic** [comment]
@scotru Same here. @aritchie this would be a really nice feature to have.
