### ISSUE TITLE
ActionSheet: Add the possibility for a cancel button

### ISSUE THREAD

**Issue by charlenni** [aritchie/acr-xamarin-forms#43]
Hello,

first of all: wonderfull work. Up to now I only use the UserDialogServices, but they are great.

Is it possible to have an entry for a cancel button for ActionSheets? On iOS, there isn't a chance to leave the dialog without this and if I use the last entry, than there is no line between the last and the second last and it looks the same as all other entries.

Best regards
Dirk

**Comment by aritchie** [comment]
This is now live on nuget https://www.nuget.org/packages/Acr.UserDialogs/  https://github.com/aritchie/userdialogs
