### ISSUE TITLE
Progress dialogs are shown as portrait orientation in landscape (iOS8)

### ISSUE THREAD

**Issue by twoog** [aritchie/acr-xamarin-forms#48]
In iOS8, when progress dialogs are shown in landscape orientation, they are displayed as if the app is in portrait mode (they displayed at a 90 degree rotation). This is due to an issue in the BTProgressHUD dependency, and can be resolved by updating to version 1.11 or above of BTProgressHUD.

**Comment by aritchie** [comment]
This will be fixed with the next release.  I'm waiting for the stable release of the unified api

**Comment by aritchie** [comment]
Update has been released to nuget with latest btprogresshud (1.15) attached
