### ISSUE TITLE
Add support for Xamarin.Forms 1.3

### ISSUE THREAD

**Issue by wizche** [aritchie/acr-xamarin-forms#59]

**Comment by karimjouini** [comment]
:+1: also patiently waiting :)

Any ETA?

Thanks a ton!

**Comment by aritchie** [comment]
When Xamarin releases the stable unified api, I will release against 1.3.1.  If you don't want to wait, fork the dev branch.

**Comment by wizche** [comment]
They postponed the release of one week

**Comment by aritchie** [comment]
Update released to nuget

**Comment by wizche** [comment]
Thanks @aritchie! You're fast!!

**Comment by GKersten** [comment]
Thank you @aritchie amazing fast!

**Comment by karimjouini** [comment]
@aritchie you rock :) !!!!!

Can I be a pain and ask for and update to 1.3.2?

1.3.1 was full of bugs, including a big regression for me (you can follow on their forum) 1.3.2 seems good for me :) but breaks with Acr.

Let me know if I can help.

You rock again ;)
