### ISSUE TITLE
Force horizontal orientation on SignaturePad

### ISSUE THREAD

**Issue by rafaelNenninger** [aritchie/acr-xamarin-forms#63]
This is a feature request (or maybe there's a workaround). I am trying to force landscape orientation when I call the SignaturePad from a button inside a stack layout inside a Content Page.

I tried changing the stack layout orientation with a bindable property and set it prior to launching the signature.

What happens is that if I have the device in Portrait orientation and click the button to launch the signature, the signaturePad is still displayed in Portrait orientation and if I click the cancel button the signaturePad disappears and the layout is in horizontal orientation. So the stack layout did change the orientation but it did not affect the signaturePad.

Is there a way to make this orientation functionality happen? 

Thank you!

This is the code I use:

private void OnSignature()
{
	
	ContentStackOrientation = StackOrientation.Horizontal;

	this.signatureService.Request(result =>
		{
			if (result.Cancelled)
				this.dialogService.Alert("Cancelled Signature");

			else
			{
				IFile file;
				using (var ms = new MemoryStream())
				{
					result.Stream.CopyTo(ms);
					SignatureBytes = ms.ToArray();
					file = this.fileSystem.AppData.CreateFile(FileName);
					using (var fs = file.OpenWrite())
					{
						fs.Write(SignatureBytes, 0, SignatureBytes.Length);
					}
				}
				SignatureImageSource = ImageSource.FromFile(file.FullName);
			}
		});
}

**Comment by aritchie** [comment]
The signature pad service has (technically) almost nothing to do with xamarin forms.  Changing the orientation in code that way will have absolutely zero effect.  You should use the SignaturePadView (xf control) if you want good control over the rendering.

I will look into adding a forced orientation for the service in the future

**Comment by markolazic88** [comment]
+1 for this request.
We are having the issue with user signature disappearing every time screen rotates. Having the ability to lock SignaturePadActivity to open only in Landscape mode would solve the issue.

Our repro steps are:
1. Open SignaturePad
2. Sign
3. Rotate screen before hitting Save. Signature is gone.
