### ISSUE TITLE
Acr.XamForms.Mobile does not exist?

### ISSUE THREAD

**Issue by tomcrusader** [aritchie/acr-xamarin-forms#65]
Trying to use samples to get basic dialogs (and toast) to work, but they seem to use a Acr.XamForms.Mobile that I can't find.

Only included namespace in PCL library is Acr.XAmForms.UserDialogs.

**Comment by aritchie** [comment]
If you download the entire sample, it is there.  If you are using a portion of the samples in your own project then remove the references to it
