### ISSUE TITLE
I need bar code sample?

### ISSUE THREAD

**Issue by sadrosdat** [aritchie/acr-xamarin-forms#67]
hi
I'm new in Xamarin . I'm wrote my first app in Xamarin up to 95% , without mvvm. I create classes an call on by one
Now I'm need QR code scanner & I found this .
I read sample but i don't know what can I do ?
I don't have any knowledge about MVVM.
I Whan Call Scanner in button click .

please help me I should give project in 2days.
```
        buttonScan.Click += (sender, e) => {

        // call scanner here, 
                               var sc=DependencyService.Get<IBarCodeService>().Read();
				var res= sc.Read();
    };

```

**Comment by aritchie** [comment]
You don't have to use this in a viewmodel, you can do it in a click, but read is an async method, so you need to await read and then work the result.
