### ISSUE TITLE
Exception with  Task<PromptResult> PromptAsync service

### ISSUE THREAD

**Issue by StephanPatrick** [aritchie/acr-xamarin-forms#68]
Hi,

When I use this code : 

PromptResult res = await DependencyService.Get<AbstractUserDialogService>().PromptAsync(
                                                                    "Veuillez saisir le mot de passe d'accès...",
                                                                    "Mot de passe",
                                                                    "Ok",
                                                                    "Annuler",
                                                                    "*",
                                                                    true);

1) In Android I see the prompt dialog but the parameter IsSecure = true  is not take in account. I see my entry in clear !!!
2) In IOS , the following exception is generate : "Object reference not set to an instance of an object"

I use the : 
Acr.XamForms.UserDialogs version .3.0.0
Xamarin.Forms version 1.3.1.6296

**Comment by aritchie** [comment]
I can't reproduce either issue.  You'll need to provide a FULL stack trace if you want my help

**Comment by akevan** [comment]
You can also use Xamarin's built in one. It works now. I recently switched my user dialogs over to it:

http://developer.xamarin.com/guides/cross-platform/xamarin-forms/working-with/pop-ups/

**Comment by aritchie** [comment]
They don't have a prompt dialog

**Comment by akevan** [comment]
Isn't that what the "DisplayActionSheet" is? That's what I use for prompts...

**Comment by aritchie** [comment]
A prompt is a text entry plus yes/no

**Comment by akevan** [comment]
var action = await DisplayActionSheet ("Do Something?", null, null, "Yes", "No");
if (action == "Yes") { ... }
else if (action == "No") { ... }

... is how I use it. Maybe not exactly the same.

**Comment by StephanPatrick** [comment]
Hi aritchie,

On IOS simulator iPhone 4s
{System.NullReferenceException: Object reference not set to an instance of an object  
at Sage.Eb.UniSignDesign.Shared.ImportCertificatesView+ctor>b__3>d__8.MoveNext () [0x00126] in c:\Projet\UniSign\NativeServices\Sage.Eb.UniSignDesign.Shared\ImportCertificatesView.cs:42 }

On winphone simulator 8.1
{System.NullReferenceException: Object reference not set to an instance of an object.   
at Sage.Eb.UniSignDesign.Shared.ImportCertificatesView.<<.ctor>b__3>d__8.MoveNext()}

I have no other information on the full stack exception.

I need to make an initialization before using your control ?

My full code is 

var Imp = new ToolbarItem
{
    Command = new Command(async () => 
    {
        try
        {
            var action = await DisplayActionSheet("Importation de l'identité", "Cancel", null, "Private KeyChain");
            if (action == "Cancel")
                return;

            if (action == "Private KeyChain")
            {
                PromptResult res = await DependencyService.Get<AbstractUserDialogService>().PromptAsync(
                                                        "Veuillez saisir le mot de passe d'accès...",
                                                        "Mot de passe",
                                                        "Ok",
                                                        "Annuler",
                                                        "******",
                                                        true);
                if (res.Ok == true)
                {
                    DependencyService.Get<IIAbstractStore>().ImportToPrivateKeyChain(PfxFileNameToImport, res.Text);
                }
            }
        }
        catch (Exception ex)
        {
        }
    }),
    Text = "Import",
    Priority = 0
};
ToolbarItems.Add(Imp);

**Comment by aritchie** [comment]
You need to make sure the nuget package is installed in each of your platform projects.  The linker strips out libraries it doesn't think are in use, you can create a dummy instance if this is the case.

**Comment by StephanPatrick** [comment]
The nuget package is deployed in each Platform projets...
How i made to create a dumy instance of an AbstractUserDialogService Interface class ?

**Comment by aritchie** [comment]
In your platform project, create an instance of UserDialogServiceImpl.  Don't use that instance, just create it so the linker does not strip the library.  

I would encourage you to read the known issues with Xamarin Forms around this as this won't be the last time you encounter this issue

**Comment by StephanPatrick** [comment]
I have made this development  and I have the same issue !!!

    public class App : Application
    {
        UserDialogServiceImpl u = new UserDialogServiceImpl();
        public App ()
        {
            MainPage = new HomeView();
        }
     }

    public class UserDialogServiceImpl : AbstractUserDialogService
    {
        public override void ActionSheet(ActionSheetConfig config) { }
        public override void Alert(AlertConfig config) { }
        public override void Alert(string message, string title, string okText)  { }
        public override Task AlertAsync(AlertConfig config)  { return null; }
        public override Task AlertAsync(string message, string title, string okText) { return null; }
        public override void Confirm(ConfirmConfig config) { }
        public override Task<bool> ConfirmAsync(ConfirmConfig config) { return null;}
        public override Task<bool> ConfirmAsync(string message, string title, string okText, string cancelText) { return null;}
        protected override IProgressDialog CreateDialogInstance() { return null; }
        public override void HideLoading() { }
        public override IProgressDialog Loading(string title, Action onCancel, string cancelText, bool show)  { return null;}
        public override void Login(LoginConfig config) { }
        public override Task<LoginResult> LoginAsync(LoginConfig config)  { return null;}
        public override Task<LoginResult> LoginAsync(string title, string message) { return null;}
        public override IProgressDialog Progress(ProgressConfig config) { return null;}
        public override IProgressDialog Progress(string title, Action onCancel, string cancelText, bool show) { return null;}
        public override void Prompt(PromptConfig config) { }
        public override Task<PromptResult> PromptAsync(PromptConfig config) { return null;}
        public override Task<PromptResult> PromptAsync(string message, string title, string okText, string cancelText, string placeholder, bool secure) { return null;}
        public override void ShowLoading(string title) { }
        public override void Toast(string message, int timeoutSeconds = 3, Action onClick = null) { }
    }
}

**Comment by aritchie** [comment]
Where did I say to recreate this class?  You have to create an instance to MY IMPLEMENTATION, not your own.  The problem is likely because the linker is stripping out my implementation from your project.  Remove the UserDialogServiceImpl you made and create var u = new Acr.XamForms.UserDialogs.iOS.UserDialogService(); iThis instance has to be made ON THE PLATFORM project, not the PCL.  For instance, in the AppDelegate
