### ISSUE TITLE
Signature pad doesn't work anymore with xamarin forms 1.3 and unified api

### ISSUE THREAD

**Issue by percramer** [aritchie/acr-xamarin-forms#69]
Hi,

the signature pad used to work but now i upgraded to the latest xamarin forms + unified api of xamarin and it doesn't work anymore (i also upgraded to your latest nugget). I needed to change the code a bit since it seems that lambda expressions aren't allowed anymore with your latest version. What i have got now is :

        SignaturePadConfiguration tmpConfig = new SignaturePadConfiguration();

            var signature = DependencyService.Get<ISignatureService>();
            var response = await signature.Request();

            if (response.Cancelled)
                return;
            else
            {
                if (_Item.Ticket_Customer_Signature == null)
                    _Item.Ticket_Customer_Signature = new byte[0];

                //var stream = new MemoryStream();
                //result.CopyTo(stream);
                //_Item.InspectionReport_Employee_Signature = stream.ToArray();
                var iostream = response.GetStream();
                iostream.Read(_Item.Ticket_Customer_Signature, 0, (int)iostream.Length);

                try
                {
                    iostream.Position = 0;
                    imgCustomerSignature.Source = ImageSource.FromStream(() => iostream);
                }
                catch (Exception ex)
                {
                    System.Diagnostics.Debug.WriteLine(ex.Message);
                }

                _Item.Ticket_Customer_SignaturePoints = response.Points;
            }

Do you see something wrong? Because it just holds on the await line and nothing happens...

**Comment by aritchie** [comment]
What platform?  I can see one issue with the way you are handling the stream which would cause issues for the secondary reads.

In the backend, I store the signature to one file and overwrite it with each request for a signature.  If your stream isn't not being disposed, you will essentially lock that file.  The below should fix things up for you

var iostream = new MemoryStream();
using (var tmp = response.GetStream())
    tmp.CopyTo(iostream);

**Comment by percramer** [comment]
Hi Artchi,

it is on iOS (hence the xamarin unified api). But i don't even get to the point where the stream is being read :-) It holds on :  var response = await signature.Request();

**Comment by aritchie** [comment]
Try the sample project, if it works fine then it is something in your code.  Like I said, secondary read requests in your project will likely deadlock because you are not disposing of the stream.

**Comment by percramer** [comment]
Hi,

it seems to be the same issue as with the rotating. The black screen that looks like it hangs is actual the signature pad overlay. Rotating the screen several times shows a signature pad, but it is totally of in size etc
