### ISSUE TITLE
Problem retrieving IUserDialogService in Windows Phone

### ISSUE THREAD

**Issue by Brosten** [aritchie/acr-xamarin-forms#70]
I tried created a small test-projekt showing a wait-dialog with the following code:
DependencyService.Get<IUserDialogService>().ShowLoading("Testing!");

It works fine with iOS and Android, but under Windows Phone 
DependencyService.Get<IUserDialogService>() returns null. 
I have the ACR nuget package installed in the WP-Project, so that shouldn't be the problem.
I have tried to target both Windows Phone 8.0 and Windows Phone Silverlight 8.1 , same problem.

Am I doing something wrong?

**Comment by aritchie** [comment]
Create a dummy instance right after you initialize xamarin forms in your winphone project (not the PCL).  The linker is stripping out the library because it doesn't think the library is in use.

Forms.Init();
new Acr.XamForms.UserDialogs.UserDialogService();

**Comment by Brosten** [comment]
Thank you for your reply.
I tried your solution, but I don't have UserDialogService as a class under UserDialogs. What I have is Acr.XamForms.UserDialogs.AbstractUserDialogService witch I can't create an instance of. 

Instead I tried new Acr.XamForms.UserDialogs.PromptConfig();
But with no luck. Any other hint of what might be wrong would be great!

**Comment by aritchie** [comment]
Make sure this is done in your platform project.  I missed the iOS namespace Acr.XamForms.UserDialogs.iOS.UserDialogService();

In any case, if anything like this is happening to you with any component in the future, instantiate the platform implementation after Forms.Init()

**Comment by Brosten** [comment]
Ahh, now I got it working! Thank you!

Just one little correction:
new Acr.XamForms.UserDialogs.WindowsPhone.UserDialogService();
