### ISSUE TITLE
Compile errors on WindowsPhone with Xamarin.Forms 1.3.2 pre1

### ISSUE THREAD

**Issue by shabeepk** [aritchie/acr-xamarin-forms#71]
After upgrading to Xamarin.Forms 1.3.2 pre1, WinPhone project stopped building, showing the following error

> Cannot resolve dependency to assembly 'Xamarin.Forms.Core, Version=1.3.1.0, Culture=neutral, PublicKeyToken=null' because it has not been preloaded. When using the ReflectionOnly APIs, dependent assemblies must be pre-loaded or loaded on demand through the ReflectionOnlyAssemblyResolve event.

The Mobile and User Dialog services nugets are causing conflict.

Some other instances of this issue are also written here:

http://forums.xamarin.com/discussion/comment/98543/#Comment_98543

**Comment by aritchie** [comment]
I don't support 1.3.2 because it isn't released yet

**Comment by shabeepk** [comment]
@aritchie Okay thanks.
