### ISSUE TITLE
Issue installing the package from NuGet

### ISSUE THREAD

**Issue by qmatteoq** [aritchie/acr-xamarin-forms#72]
I've installed the latest package from NuGet in my Xamarin Forms 1.3 project, but I can't get the GeoLocation service to work properly.
I've tried to start from scratch with a sample app and I'm always able to reproduce it.
Here is what I did:

1. I've created a new Xamarin Forms with a PCL as a shared project
2. I've installed, using NuGet, the package Acr.XamarinForms.Mobile (https://www.nuget.org/packages/Acr.XamForms.Mobile/)
3. In my code, I try get a reference to the GeoLocation service using the Xamarin DependencyService, like I've seen in the sample:

` 
private async void OnGetPositionClicked(object sender, EventArgs e)
{
    IGeoLocator locator = DependencyService.Get<IGeoLocator>();
    Position position = await locator.GetPositionAsync();
    Debug.WriteLine(position.Latitude);
}
` 
Unfortunately, the object returned by the DependencyService class is always null. What am I doing wrong? Did I miss to initialize something in the code?

Thanks in advance!

**Comment by aritchie** [comment]
Create a dummy instance of the implementation in your platform project.  The linker is stripping the platform project out.

**Comment by qmatteoq** [comment]
Thanks, I've created an empty implementation of the IGeoLocator interface (all the methods simply throw a new NotImplementedException) decorated with the following attribute:

[assembly: Dependency(typeof(GeoLocator))]

where GeoLocator's namespace is Acr.XamForms.Mobile.Locations;

Now it seems it's working fine, since the DependencyService correctly returns an implementation of the IGeoLocator interface. However, as soon as I try to call the GetPositionAsync() method, I always get the following exception:

A first chance exception of type 'System.Threading.Tasks.TaskCanceledException' occurred 
A task was canceled.

Do you have any idea what's going on? Thanks!

**Comment by aritchie** [comment]
It is finding your implementation.  Create a dummy instance of my implementation.

So right after Forms.Init(); put the APPROPRIATE platform namespace to the implementation.
new Acr.XamForms.Mobile.Location.iOS.GeoLocatorImpl()

**Comment by qmatteoq** [comment]
Thanks, now I've fully realized what you mean with "create a dummy instance".
What about in case a specific implementation of the class is missing for one platform?

For instance, I can't find a GeoLocator implementation for Windows Phone in the Acr.XamForms.Mobile.Location.WindowsPhone namespace.

**Comment by qmatteoq** [comment]
It seems that I'm hitting the following issue: https://github.com/xamarin/Xamarin.Mobile/issues/16
Did you ever see that?

**Comment by aritchie** [comment]
Oiiiii this issue has absolutely nothing to do with what you filed.  That is an android specific problem and I see you've linked it to this....

The cancelled operation is likely permissions issue.  See if there is more to the exception stack.

**Comment by qmatteoq** [comment]
Yes, I suspected it wasn't connected to your library. Thanks for the support!
