### ISSUE TITLE
LoginResult (from UserDialogs) is set to true when Cancelling on iOS

### ISSUE THREAD

**Issue by PaulAchess** [aritchie/acr-xamarin-forms#73]
Hi,
When cancelled, the login dialog retuns « true » as a result on iOS Devices instead of false.

The bug comes from the line 94 of UserDialogService of iOS :        

93 - dlg.AddAction(UIAlertAction.Create(config.OkText, UIAlertActionStyle.Default, x => config.OnResult(new LoginResult(txtUser.Text, txtPass.Text, true))));
94 - dlg.AddAction(UIAlertAction.Create(config.CancelText, UIAlertActionStyle.Default, x => config.OnResult(new LoginResult(txtUser.Text, txtPass.Text, **true**))));

Second line should pass false instead of true.
I absolutely have no idea how to help fixing it, I've never done a pull request unfortunately :-/

**Comment by aritchie** [comment]
No worries.  I can fix it.  Thanks for the report

**Comment by PaulAchess** [comment]
Glad I could be of some help !
