### ISSUE TITLE
64 bit support - seem to be an issue

### ISSUE THREAD

**Issue by baerial** [aritchie/acr-xamarin-forms#77]
Your code is outstanding… wish I could do what you do.

One thing I did discover with your barcode scanner is if you try to use the newest version and 
compile it will give you an exception error….sorry I dis not record the issue but I can tell you that using the 32 bit version of  ZXing 1.4.6 … solved the compiler exception.

One reason I am posting in the exception area of GitHub is I would like to contact you and do not know hoes to do that….. if you are following these posts please contact me at cbaldwin@michenerallen.com

PS… Your code as far as i am concerned is outstanding ….

**Comment by aritchie** [comment]
The current nuget package I released does not use zxing.net.mobile 1.4.6 because it doesn't support the unified API.  It uses 1.4.7.1.  The issue is with your setup somehow.  

I would suggest removing the nuget package and reinstalling them all.
