### ISSUE TITLE
BarCodeScanner: Get warning when calling from nested NavigationPages

### ISSUE THREAD

**Issue by charlenni** [aritchie/acr-xamarin-forms#78]
Hello,

first of all thank you for your efforts. Great work!

I have a problem with the BarCodeScanner part of your library. I set all things up on the first page of my app (is the fastest to test the bahavior). There was all working well, so I transfered the code to a part of the app, which is in the deeper nested. I replace the normal NavigationPage with a new modal one. In this NavigationPage environment I call the scanner and get the following warning:

    Warning: Attempt to present <ZXing_Mobile_ZXingScannerViewController: 0x201ee9e0> on <Xamarin_Forms_Platform_iOS_PlatformRenderer: 0x18847750> whose view is not in the window hierarchy!

The scanner page isn't shown.

I search for the problem and found the following StackOverflow message: http://stackoverflow.com/questions/20731716/monotouch-zxing-presenting-zxingscannerviewcontroller-failed. 

It seems, that there are problems with the different NavigationPages I use. I use 1.3.3-pre2 and the NuGet version from today of your library. The problem exists on iOS.

Is there a workaround for this problem?

Thanky you very much in advance for your help.

Best regards,
Dirk

**Comment by aritchie** [comment]
I haven't come across this issue myself.  Can you submit a gist with the issue?

**Comment by charlenni** [comment]
It seems, that it is not a problem from your library, but from ZXing.Net. If you create a first NavigationPage and place a button on this page, which creates another NavigationPage, that is than modal pushed onto the first NavigationPage (with PushModalAsync) than you get this error.

It is enough to create the ZXing.Net object with the active UIViewController as parameter. I will send you some code and detailed explanations, if I turned the Mac on later :)

**Comment by aritchie** [comment]
Internally, I suspect zxing is trying to find the top level window/view controller to present on.  This isn't an exact science unfortunately.

If you are using the user dialog library, can you try running a loading dialog on the page where barcode scanner is attempting to launch from.  It means that my "top scanner" works and could be applied to zxing.net.mobile.

**Comment by charlenni** [comment]
I use only parts, but the functions to get the GetTopView() are the same as in your library. And yes, I could display ActionSheets on the modal NavigationPage.

I created a workaround. I call in the Read method of the BarCodeScanner object the following code:

			var controller = ((UIViewController)((ExtendedNavigationPage)App.GameNavigation).ViewController);
			var scanner = new MobileBarcodeScanner(controller);

The `((ExtendedNavigationPage)App.GameNavigation).ViewController)`is a extension of a normal NavigationPage. On iOS I get the ViewController by

		protected override void OnElementChanged(VisualElementChangedEventArgs e)
		{
			base.OnElementChanged(e);

			((ExtendedNavigationPage)Element).ViewController = this.ViewController;
                }
 
This works.

**Comment by aritchie** [comment]
This was fixed in Acr.BarCodes

**Comment by CesarCavazos97** [comment]
Hi, I have the same problem, I'm using your var controller = ((UIViewController)((ExtendedNavigationPage)App.GameNavigation).ViewController);
But what is the ExtendedNavigationPage, GameNavigation and the .ViewController? Its a classo what? Can you pass me the code? Please
