### ISSUE TITLE
SignaturePad iPad Support

### ISSUE THREAD

**Issue by percramer** [aritchie/acr-xamarin-forms#80]
Hi,

sorry to write about this again but i found some new info. Hi, It seems to be the same issue as with the rotating. The black screen that looks like it hangs is actual the signature pad overlay. Rotating the screen several times shows a signature pad, but it is totally of in size etc

![signature error1](https://cloud.githubusercontent.com/assets/2083225/6116886/91434300-b0b0-11e4-89f0-309ea9cc07a7.png)
![signature error2](https://cloud.githubusercontent.com/assets/2083225/6116888/916311a8-b0b0-11e4-8043-8213aa17251f.png)
![signature error3](https://cloud.githubusercontent.com/assets/2083225/6116887/9160f706-b0b0-11e4-945e-51f515f650b8.png)

**Comment by deckertron9000** [comment]
I'm going to look into this for an upcoming project. @aritchie do you have any quick suggestions on how to make this work nicely on iPad or should I just wing it?
