### ISSUE TITLE
Could you add a Cancel-button to the ActionSheet?

### ISSUE THREAD

**Issue by Brosten** [aritchie/acr-xamarin-forms#81]
We would like the option to have a Cancel-button on the ActionSheet dialog.
About the same way as the Page.DisplayActionSheet() method has in Xamarin Forms.

Would it be possible? In case, when could we expect it?

Regards Andreas

**Comment by aritchie** [comment]
It is possible.  I just haven't had the need for it.  You can submit a PR if you need it now.

**Comment by charlenni** [comment]
I did this for my own project for Android and iOS. I don't have a solution for WinPhone. Should I post my changes?

**Comment by charlenni** [comment]
In the common project I removed the comments for the Cancel property and the SetCancel() method. 

While looking around, what I changed, I see, that you changed much in your code. So it is not possible to give the correct code, but an outline what I did.

On iOS I added a cancel button as last button:

					if (config.Cancel != null)
					{
						action.AddButton(config.Cancel.Text);
						action.CancelButtonIndex = config.Options.Count;
					}

and checked in the clicked delegate, if cancel is clicked:

						if (btn != null && btn.ButtonIndex == config.Options.Count && config.Cancel != null && config.Cancel.Action != null)
							config.Cancel.Action();

That's all on iOS.

On Android I replace the ActionSheet constructor with the following:

		public override void ActionSheet(ActionSheetConfig config)
		{
			var array = config
                .Options
                .Select(x => x.Text)
                .ToArray();

			if (config.Cancel != null)
				Device.BeginInvokeOnMainThread(() => 
    	            new AlertDialog
        	            .Builder(Forms.Context)
            	        .SetTitle(config.Title)
                	    .SetItems(array, (sender, args) => config.Options[args.Which].Action())
						.SetNegativeButton(config.Cancel.Text, (sender, EventArgs) => config.Cancel.Action())
	                    .Show()
				);
			else
				Device.BeginInvokeOnMainThread(() => 
					new AlertDialog
					.Builder(Forms.Context)
					.SetTitle(config.Title)
					.SetItems(array, (sender, args) => config.Options[args.Which].Action())
					.Show()
				);
		}

That's it.

**Comment by aritchie** [comment]
@charlenni Thanks.  I think I have a few ideas how to do this with the destructive option as well

**Comment by aritchie** [comment]
I released this on the new replacement library.  This library will actually support xamforms alot better going forward.  https://www.nuget.org/packages/Acr.UserDialogs/  https://github.com/aritchie/userdialogs

**Comment by Brosten** [comment]
Ahh, perfect!

The cancel-button works fine =)

 

However, now the dependency-problem to xamarin 1.3.2.0 is back for my WinPhone project.

 

How can this be a problem anyway? Shouldn’t the acr-tools be able to work for more then exactly one xamarin-forms version?

 

Regards Andreas

 

Från: Allan Ritchie [mailto:notifications@github.com] 
Skickat: den 11 februari 2015 04:21
Till: aritchie/acr-xamarin-forms
Kopia: Brosten
Ämne: Re: [acr-xamarin-forms] Could you add a Cancel-button to the ActionSheet? (#81)

 

I released this on the new replacement library. This library will actually support xamforms alot better going forward. https://www.nuget.org/packages/Acr.UserDialogs/ https://github.com/aritchie/userdialogs
