### ISSUE TITLE
DependencyService.Get<IFileSystem>() does not work on Windows Phone

### ISSUE THREAD

**Issue by fonix232** [aritchie/acr-xamarin-forms#83]
I've been trying to get IFileSystem work in a XamForms app. On iPhone and Android, the following code works without an issue:

```c#
var fs = DependencyService.Get<IFileSystem>();
```

However on Windows Phone 8.1 (project targets WP80 Silverlight), the same code returns null.
Checked the NuGet libraries, they do contain the FileSystem, etc. implementations of IFileSystem.

**Comment by qmatteoq** [comment]
Try to create a dummy instance of the FIleSystem class right in the MainPage.xaml.cs class, after the Xamarin Forms initialization and before loading the application. That's what I had to do to make some of the services included in the library to work, like the GeoLocator.

**Comment by aritchie** [comment]
https://github.com/aritchie/acr-xamarin-forms/issues/86
