### ISSUE TITLE
Problems with UserDialog and SignaturePad after updating

### ISSUE THREAD

**Issue by cvarelae** [aritchie/acr-xamarin-forms#85]
Hi mates,

I had an app with Xamarin.Forms 1.25 and previous version of acr.xamarin.forms. I updated my app to xamarin forms 1.33 and the latest version of ac.xamarin-forms.

Before updating, user dialog and signature pad worked perfectly, and now They do not work.

The problem is when I create the service, where i get a null. For example I have the next code:

dialogService = DependencyService.Get< Acr.XamForms.UserDialogs.IUserDialogService >();

But the result is always null, and it worked with the previous version.

This is the problem with the signature. I used this code, which it worked perfectly also:

private SignaturePadView signature =
                new SignaturePadView()
                {
                    StrokeWidth = 3f,
                    StrokeColor = Color.Black,
                    SignatureLineColor = Color.Black,
                    BackgroundColor = Color.White,
                    HorizontalOptions = LayoutOptions.FillAndExpand,
                    VerticalOptions = LayoutOptions.FillAndExpand,
                    IsVisible = true,
                    PromptText = ".",
                    PromptTextColor = Color.White,
                    ClearText = ".",
                    ClearTextColor = Color.White,
                    CaptionTextColor = Color.Black,
					CaptionText = L10n.GetLiteral("Signature"),
                };

But now This does not show anything... 

What is the difference of the new versions? How can i fix that?

Thanks a lot in advance!

**Comment by aritchie** [comment]
https://github.com/aritchie/acr-xamarin-forms/issues/86
