### ISSUE TITLE
SignaturePad: Some lines are removed

### ISSUE THREAD

**Issue by cvarelae** [aritchie/acr-xamarin-forms#94]
Hi,

When I use the signaturePadView like in the sample "XAML Signature Pad" and I write a name, letter by letter, lifting the finger, some letters are removed (try to write "PABLO" for example).

But when I use the other example ("SignaturePad Service"), it works perfectly. No line is removed.

The problem is that "SignaturePad Service" creates a new UIViewController, a new screen in Xamarin, and I want to use the signaturepadview as other control on my page. How can i achieve to use a signaturepadview like in this example on my page?

Thanks a lot in advance!

**Comment by cvarelae** [comment]
Sorry for disturbing you again, but i can't find the original issue to see the solution. Thanks again

**Comment by aritchie** [comment]
There is no solution.  It is filed as a bug.  I likely won't fix it because of the constant changes with xamarin forms

**Comment by cvarelae** [comment]
Oh, What a pity. I understand you, there are several changes each xamarin forms version...

Thanks a lot for your effort, and for sharing your work and knowledge.
