### ISSUE TITLE
Action Sheet on iPad a bit weird

### ISSUE THREAD

**Issue by xeterixon** [aritchie/acr-xamarin-forms#96]
There seems to be a rather annoying visual difference between iOS7 and iOS8 when displaying an Action Sheet. See the screenshots below.
I assume it is has to do with using UIActionSheet on iOS7 and UIAlertController on iOS8.
One would like to be able to set some kind of anchoring point for iOS8 (at least).
Any known work-around for this?

BTW, thanks for a great library. Like it a lot...

iOS7
![sheet_ipad_7](https://cloud.githubusercontent.com/assets/7112456/6525162/7105a80c-c402-11e4-96aa-76c64ea5e784.png)
iOS8
![sheet_ipad_8](https://cloud.githubusercontent.com/assets/7112456/6525161/71021e26-c402-11e4-8e2c-77adc86fce79.png)

**Comment by jaco3319** [comment]
Will this issue be addressed some time in the near future? 
I'm seeing this behavior as well, and it really does not look good.. :(

Is there a workaround i have missed?

Thanks.

**Comment by aritchie** [comment]
@jaco3319 Will you be submitting a pull request at some point in the near future?  I don't have time to fix every single defect and feature request coming in.  I'm glad you get value out of this library, but it is for my needs first and foremost.  Seeing as I almost never target ipad's, this is not giving me grief directly at the moment.

**Comment by aritchie** [comment]
Fixed in Acr.UserDialogs 3.4
